### ISSUE TITLE
Fauna shell crashes while typing

### ISSUE THREAD

**Issue by brunosmm** [fauna/fauna-shell#66]
Hello,

The crashes happen once I type the . to fill the email on the login command, below the crash info:

```
behorse> Login(Match(Index("users_by_email), "bruno@behorse.Uncaught TypeError: Cannot read property 'length' of undefined
    at runQueries (/usr/local/Cellar/fauna-shell/0.11.5/libexec/lib/node_modules/fauna-shell/src/lib/misc.js:384:19)
behorse> /usr/local/Cellar/fauna-shell/0.11.5/libexec/lib/node_modules/fauna-shell/src/lib/misc.js:384
  if (expressions.length == 1) {
                  ^

TypeError: Cannot read property 'length' of undefined
    at runQueries (/usr/local/Cellar/fauna-shell/0.11.5/libexec/lib/node_modules/fauna-shell/src/lib/misc.js:384:19)
    at /usr/local/Cellar/fauna-shell/0.11.5/libexec/lib/node_modules/fauna-shell/src/commands/shell.js:86:16
    at finishExecution (repl.js:411:7)
    at defaultEval (repl.js:497:7)
    at bound (domain.js:426:14)
    at runBound (domain.js:439:12)
    at REPLServer.replEvalPromise [as eval] (/usr/local/Cellar/fauna-shell/0.11.5/libexec/lib/node_modules/fauna-shell/src/commands/shell.js:71:5)
    at REPLServer.complete (repl.js:1277:10)
    at REPLServer.completer (repl.js:620:14)
    at showCompletionPreview (internal/repl/utils.js:191:10)
    at showPreview (internal/repl/utils.js:328:5)
    at REPLServer.repl._refreshLine (internal/repl/utils.js:419:5)
    at REPLServer.Interface.prompt (readline.js:301:10)
    at REPLServer.displayPrompt (repl.js:1036:8)
    at Domain.debugDomainError (repl.js:597:12)
    at Domain.emit (events.js:315:20)
    at Domain.EventEmitter.emit (domain.js:482:12)
    at Domain._errorHandler (domain.js:246:23)
    at Object.<anonymous> (domain.js:156:29)
    at process._fatalException (internal/process/execution.js:164:29)
```
![image](https://user-images.githubusercontent.com/1554850/97783638-0dc2a500-1b91-11eb-831e-c46830cebf96.png)

Versino:   fauna-shell/0.11.5 darwin-x64 node-v12.17.0

Let me know if you need further info.

**Comment by dotchev** [comment]
Just hit the same issue. When I open the shell and type a dot after any other char, e.g. "a.", it crashes with the error above.
```
$ fauna -v
fauna-shell/0.11.5 darwin-x64 node-v15.1.0
```
